<?php
/**
 * Pickit - Override Template - Checkout Shipping Method
 *
 */
?>
<?php /** @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available */ ?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
	<p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
	<dl class="sp-methods">
		<?php $shippingCodePrice = array(); ?>
		<?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
		<dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
		<dd>
			<?php if($this->getCarrierName($code) == Mage::getStoreConfig('carriers/pickitconfig/title',Mage::app()->getStore())): ?>
				<?php $linkText = Mage::getStoreConfig('carriers/pickitconfig/link_text',Mage::app()->getStore()); ?>
				<?php $urlPickit = $this->getUrlPickit(); ?>
				<?php if($this->getUrlPickit() != ""): ?>
					<?php if(Mage::getStoreConfig('carriers/pickitconfig/fancybox') == 0 && Mage::getStoreConfig('carriers/pickitconfig/version_fancy') == 0): ?>
							<a href="<?php echo $this->getUrlPickit(); ?>" id="pickit_link" class="iframe"><?php echo $linkText; ?></a>
						<?php else: ?>
							<a href="<?php echo $this->getUrlPickit(); ?>" id="pickit_link" data-fancybox-type="iframe"><?php echo $linkText; ?></a>
						<?php endif; ?>
				<?php else: ?>
					<a href="javascript:void(0)">Servicio no disponible</a>
				<?php endif; ?>
				<script type="text/javascript">
				var version = "<?php echo Mage::getStoreConfig('carriers/pickitconfig/fancybox'); ?>";
				var fbv 	= "<?php echo Mage::getStoreConfig('carriers/pickitconfig/version_fancy'); ?>";
				if(version == 0 && fbv == 0) {
					//alert('viejo');
					jQuery(document).ready(function() {
						window.addEventListener('message', function (event) {
							if (event.data == 'close') {
								jQuery.fancybox.close();
							}
						}, false);
						jQuery("a#pickit_link").fancybox({
							'width'				: 985,
							'height'			: 637,
							'showCloseButton'	: false,
							'onClosed'			: function() {									
								jQuery.ajax({
									url: "<?php echo Mage::getUrl('pickit/indexpickit/setPunto', array('_secure' => true)); ?>",
									type: "GET",
									success: function (response) {
										jQuery('li.pickit').hide();
										jQuery('a#pickit_link').after("<p id=\"loader\">Cargando...<img src='<?php echo $this->getLoaderUrl(); ?>' /></p>");
										shipping.save();
									}
								});
							}
						});
					});
				} else {
					jQuery(document).ready(function() {
						window.addEventListener('message', function (event) {
							if (event.data == 'close') {
								jQuery.fancybox.close();
							}
						}, false);
						jQuery("a#pickit_link").click(function() {
							jQuery("a#pickit_link").fancybox({
								maxWidth	: 1200,
								autoSize	: true,
								maxHeight	: 750,
								fitToView	: false,
								width		: 985,
								height		: 637,
								autoSize	: false,
								closeBtn	: false,
								openEffect	: 'none',
								closeEffect	: 'none',
								iframe: {
									scrolling : 'no',
									preload   : true
								},
								beforeClose: function() {									
									jQuery.ajax({
										url: "<?php echo Mage::getUrl('pickit/indexpickit/setPunto', array('_secure' => true)); ?>",
										type: "GET",
										success: function (response) {
											jQuery('li.pickit').hide();
											jQuery('a#pickit_link').after("<p id=\"loader\">Cargando...<img src='<?php echo $this->getLoaderUrl(); ?>' /></p>");
											shipping.save();
										}
									});
								}
							});
						});
					});
				}
				</script>
			<?php endif; ?>
			<ul>
				<?php 
				$_sole = $_sole && count($_rates) == 1;
				foreach ($_rates as $_rate): ?>
				<?php if(($_rate->getCode() == 'pickitconfig_pickitconfig' && $this->validarIdPuntoPickit()) || $_rate->getCode() != 'pickitconfig_pickitconfig'): ?>
					<?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
					<li <?php if($_rate->getCode() == 'pickitconfig_pickitconfig'): ?> class="pickit" <?php endif; ?>>
						
						<?php if ($_rate->getErrorMessage()): ?>
							<ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
						<?php else: ?>
							<?php if ($_sole) : ?>
								<span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" /></span>
							<?php else: ?>
								<input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo '' ?> class="radio"/>

								<?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
									<script type="text/javascript">
										//<![CDATA[
										lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
										//]]>
									</script>
								<?php endif; ?>
							<?php endif; ?>
							<label for="s_method_<?php echo $_rate->getCode() ?>">
								<?php if($_rate->getCode() == 'pickitconfig_pickitconfig'): ?>
									<?php
									$detalles = split(" / ",$_rate->getMethodTitle());
									echo $detalles[0]."</br>";
									?>
									<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
									<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
									<?php echo $detalles[1]." ".$_excl."</br>"; ?>
									<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
										(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
									<?php endif; ?>
									<?php echo $detalles[2]; ?>
								<?php else: ?>
									<?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
									<?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
									<?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
									<?php echo $_excl; ?>
									<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
										(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
									<?php endif; ?>
								<?php endif; ?>
							</label>
						<?php endif ?>
					</li>
				<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</dd>
	<?php endforeach; ?>
</dl>
<script type="text/javascript">
//<![CDATA[
<?php if (!empty($shippingCodePrice)): ?>
	var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
<?php endif; ?>

$$('input[type="radio"][name="shipping_method"]').each(function(el){
	Event.observe(el, 'click', function(){
		if (el.checked == true) {
			var getShippingCode = el.getValue();
			<?php if (!empty($shippingCodePrice)): ?>
			var newPrice = shippingCodePrice[getShippingCode];
			if (!lastPrice) {
				lastPrice = newPrice;
				quoteBaseGrandTotal += newPrice;
			}
			if (newPrice != lastPrice) {
				quoteBaseGrandTotal += (newPrice-lastPrice);
				lastPrice = newPrice;
			}
		<?php endif; ?>
		checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
		return false;
	}
});
});
//]]>
</script>
<?php endif; ?>
<script type="text/javascript">
	var activadoPickit = "<?php echo Mage::getStoreConfig('carriers/pickitconfig/active'); ?>";
	//alert(activadoPickit);
	if(activadoPickit != 0) {
		if(jQuery('li.pickit input:radio[name="shipping_method"]').length) {
			jQuery('li.pickit input:radio[name="shipping_method"]').attr('checked', 'checked');
			jQuery('a#pickit_link').text('Cambiar punto de retiro');
		}

		jQuery('input:radio[name="shipping_method"]').change(function() {
			if(jQuery('li.pickit input:radio[name="shipping_method"]').is(':checked')) {
			}
		});
	} else {
		jQuery('input:radio[name="shipping_method"]').first().attr('checked', 'checked');
	}
</script>